#!/system/bin/sh
svc wifi disable
sleep 1
rm /system/etc/firmware/ti-connectivity/wl1271-nvs.bin
sleep 1
calibrator plt autocalibrate wlan0 /system/lib/modules/wl12xx_sdio.ko /system/etc/wifi/ini_files/127x/TQS_S_2.6.ini /system/etc/firmware/ti-connectivity/wl1271-nvs.bin
sleep 1
svc wifi enable
sleep 1

